# Generated by Django 5.0.2 on 2024-04-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='index',
            field=models.IntegerField(blank=True, default=-1, help_text='Вкажіть порядковий номер для сортування', verbose_name='Індекс'),
        ),
    ]
